inp = str(input("file: "))
file = open(inp, "r")
txt = file.read()
print("nb char: " + str(len(txt)))
print("nb lines: " + str(len(txt.split("\n"))))
print("nb words: " + str(len(txt.split(" "))))
distinct = list(set(txt.split(" ")))
print("distinct: ", end = "")
print(distinct)
first = " ".join(txt.split(" ")[0:19])
print("20 1st words: " + first)